### PR TITLE
updated favicon

### PR DESCRIPTION
**Pull request by nagamukesh**
I have updated the favicon with a peacock feather which I felt is a very apt favicon to show the essence of the the website in a very small picture/icon

image

please suggest any changes

### CODE REVIEW

**Comment by sameer-soni** [comment]
@nagamukesh transparent background and only feather logo with more contrast and saturation?

**Comment by nagamukesh** [comment]
ok
I will try to make those changes
thanks for your valuable suggestion

**Comment by sameer-soni** [comment]
@nagamukesh no working on this?

**Comment by nagamukesh** [comment]
Sorry, I am outside my house for some days due to medical emergency
I will try to update the relevant favicon by tomorrow 
Please understand

**Comment by nagamukesh** [comment]
i have updated the icon according to the suggestions
image
here is the new favicon

**Pull request merged**
