### PR TITLE
Added the responsive ness in the website

### PR DESCRIPTION
**Pull request by suraj-9849**
issue : #123 
I add the responsive ness in the Navbar.js ,home.js and Homeque.js

### CODE REVIEW

**Comment by suraj-9849** [comment]
Please add the Label like level1,level2

**Comment by sameer-soni** [comment]
@suraj-9849 can you resolve the conflicts

**Comment by suraj-9849** [comment]
@sameer-soni I have resolved the error and let me tell u that there must no gap between the level 3 it should be like level3 it seems I listened it from the program manager of GSSOC(youtube) so can u change the label to level3 but not level 3

**Comment by suraj-9849** [comment]
@sameer-soni I resolved the issue and can u label it as level 3 because u label it in the issue as label 3 and here as label 2 so

**Comment by suraj-9849** [comment]
@sameer-soni brother please change the label here it is level 2 here and in the issue #123 it is level 3. GSSOC will think as the spam so please change it to lvl3 here also

**Pull request merged**
