### PR TITLE
Added verse of the day functionality, issue #165

### PR DESCRIPTION
**Pull request by its-kritika**
Resolves issue #165

I have added the Verse of the Day functionality to the application using React. Now on, everyday we will get a verse, better as 'Gita ka Gyaan' fetched randomly among the numerous shloks of Bhagvad Gita. This will enhance the user interaction making the application more familiar to the users.

Here I have shared the screenshot. 
Screenshot (394)

**Note:** These verses will get updated at 12:00 AM everyday!!

### CODE REVIEW

**Comment by its-kritika** [comment]
@sameer-soni 
It is showing that branch has conflicts, do I need to resolve it to make a PR? Can you help me with that?

**Comment by Aditya13s** [comment]
> @sameer-soni It is showing that branch has conflicts, do I need to resolve it to make a PR? Can you help me with that?

Try to rebase it using `git rebase main`

**Comment by its-kritika** [comment]
> > @sameer-soni It is showing that branch has conflicts, do I need to resolve it to make a PR? Can you help me with that?
> 
> Try to rebase it using `git rebase main`

The following msg is getting displayed   -> 'Current branch main is up to date.' Do I need to bring changes of dev branch to main?

**Comment by Aditya13s** [comment]
use `git fetch` and then `git pull`

**Comment by its-kritika** [comment]
It is yet showing that my branch is up to date. I think there are some changes coming from pr #149. I found that all other prs are made to main branch ( other than pr #149). Should I make a pr to main branch of this project?

**Comment by Aditya13s** [comment]
> `its-kritika` wants to merge 1 commit into `Omkar-Sonawane-23:Dev` from `its-kritika:main`

you are pushing from your main branch to Dev brach of this project, either you have to rebase with this project's Dev branch or you can push your changes to main branch.

**Comment by its-kritika** [comment]
Okay I'll raise a pr to main branch

**Pull request closed without merging**
