### PR TITLE
added morale boosting quotes in the home page

### PR DESCRIPTION
**Pull request by Leorasaharia**

### CODE REVIEW

**Comment by Omkar-Sonawane-23** [comment]
Please Provide Us What You Have Done here

**Comment by Leorasaharia** [comment]
Yes sir, I added some of the the quotes from bhagvad gits about krishna on the home page till now will try to make more responsive and other changes mentioned later on step by step thankyou

**Comment by Omkar-Sonawane-23** [comment]
No Functionaity 

image

**Comment by Leorasaharia** [comment]
Sorry sir, I will fix the ui .. it was showing correctly on my system

**Pull request closed without merging**
